apiVersion: v1
kind: Secret
metadata:
  name: {{ include "todoapp.fullname" . }}-secrets
  labels:
    {{- include "todoapp.labels" . | nindent 4 }}
type: Opaque
data:
  ConnectionStrings__DefaultConnection: {{ .Values.secrets.connectionString | b64enc | quote }}
  Jwt__Key: {{ .Values.secrets.jwtKey | b64enc | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgres.credentials.password | b64enc | quote }}
