apiVersion: v1
kind: Service
metadata:
  name: todoapp-frontend
  namespace: todoapp
  labels:
    app.kubernetes.io/name: todoapp
    app.kubernetes.io/component: frontend
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: todoapp
    app.kubernetes.io/component: frontend
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
